SlicerIGT/SlicerIGT

PlusRemote/PlusRemote.py

This issue caused runtime error while reconstructing prostate phantom dataset.
On a related note: after fixing this issue, the operation times out before getting the reconstructed volume back from the server. Should the timeout parameter be configurable? Not sure if it has any negative consequences, since even after the timeout the reconstructed volume is received in Slicer when ready.

Add check for non-empty text to fix runtime error

---

MarkupsToModel/qSlicerMarkupsToModelModuleWidget.cxx
MarkupsToModel/qSlicerMarkupsToModelModuleWidget.h

Fixes typos where "Toggle" was written as "Toogle".

Change "Toogle" to "Toggle"

---

PlusRemote/PlusRemote.py

Without this change, plus server stops and complains about not having the correct file writer, since the timestamp becomes part of the extension

Better Nrrd support

---

MarkupsToModel/Logic/vtkSlicerMarkupsToModelLogic.cxx
MarkupsToModel/Logic/vtkSlicerMarkupsToModelLogic.h
MarkupsToModel/MRML/vtkMRMLMarkupsToModelNode.cxx
MarkupsToModel/MRML/vtkMRMLMarkupsToModelNode.h
MarkupsToModel/Resources/UI/qSlicerMarkupsToModelModuleWidget.ui
MarkupsToModel/qSlicerMarkupsToModelModuleWidget.cxx

These are enhancements that improve both the predictability and flexibility of curve fitting in MarkupsToModel.
- Interpolating curves will now pass through the control points (as they should have)
- There are additional options that allow this module to better emulate the original behaviour of CurveMaker

Markups to model ring mode

---

Guidelet/GuideletLib/GuideletFrame.py

Modified the GUI in the settings panel of the guidelet to have a
ctkPathLineEdit widget instead of a QLineEdit so that users can browse
through to choose their save-to directory instead of manually entering
it.

ENH: Added ctkPathLineEdit widget to Guidelet Settings

---

Guidelet/GuideletLib/UltraSound.py
Guidelet/GuideletLoadable.py

If set to True (False by default in Guidelet base) in the user's
guidelet parameters, the recording button will remain clickable even if
the plus connector is frozen.

Added Recording Always Enabled Parameter.

---

Guidelet/GuideletLib/Guidelet.py
Guidelet/GuideletLib/UltraSound.py
Guidelet/GuideletLoadable.py

This allows the option of setting the name for the capture device. If
set to '', PLUS will not record to file. This can be used to allow the
Sequences extension to handle saving of recordings within Slicer instead
of PLUS.

Added PLUS Capture Device parameter and Wait Cursor to Guidelet Base.

---

ToolWatchdog/qSlicerWatchdogModule.cxx

This commit updates the ToolWatchdog module to work with Slicer
following r26540 (BUG: Fix initialization of module displayable managers)
See http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26540

Ensure displayable manager are registered with Slicer >= 4.9

---

OpenIGTLinkRemote/Widgets/qSlicerOpenIGTLinkRemoteQueryWidget.cxx

Changing the query data type when the list has been populated with items will cause the items in the list to become empty.
Selecting one of these empty items and clicking "Get selected items" will cause Slicer to crash.
Fix is two-fold:
- After query data type is changed, set the number of rows to zero, so that there are no empty items in the list.
- When attempting to get a selected item in querySelectedItem(), check to see if the item exists. If it does not, print an error message and skip the currently selected item.

BUG: Fix bug in OpenIGTLink Remote causing Slicer to crash

---

Guidelet/GuideletLib/Guidelet.py
Guidelet/GuideletLib/UltraSound.py
Guidelet/GuideletLoadable.py

Replaced usages of slicer.util.getNode with slicer.mrmlScene.GetNode functions because slicer.util.getNode behavior was modified in Slicer 4.9. This change is also backwards compatible with Slicer 4.8.

Replaced usages of slicer.util.getNode in Guidelet

---

FiducialRegistrationWizard/Logic/vtkSlicerFiducialRegistrationWizardLogic.cxx
FiducialsToModelRegistration/FiducialsToModelRegistration.py
ModelRegistration/ModelRegistration.py

This is related to the recent changes in Slicer, SlicerExecutionModel, and BRAINSTools, the goal of which is to update registration modules to have the output transforms reference the inputs (images/fiducial lists/models, fixed and moving separately).

ENH: Add node references in the registration modules

---

Guidelet/GuideletLoadable.py

Map (along with several other functions) no longer return lists in Python 3, this casts the iterable into a list to allow the rest of the function to execute as normal.

Add cast to list around map for Python 3 compatibility

---

Guidelet/GuideletLib/Guidelet.py
Guidelet/GuideletLib/__init__.py
Guidelet/__init__.py

I added absolute imports. I changed the unicode() function to the str.encode() string method for Python 3. I removed a condition that checked unicode() in addition to str() because they are now the same in Python 3.

Fixed Python 3 absolute imports and unicode function. 

---

Guidelet/GuideletLib/Guidelet.py

Creating two layouts for the same frame caused the error "QLayout: Attempting to add QLayout "" to QFrame "", which already has a layout" to be thrown when starting a Guidelet. This is a problem if one tries to rely on the error icon for actual errors, and makes reading logs more difficult.

BUG: Fix error on startup in Guidelet

---

FiducialsToModelRegistration/FiducialsToModelRegistration.py

The instantiation of the module logic was added to module setup function. Such behaviour is in-line with the ScriptedLoadableModule template generated by Slicer and gives python scripts access to the module logic.
In addition a test case for this module was added resolving the [Add FiducialsToModelRegistration tests #62](https://github.com/SlicerIGT/SlicerIGT/issues/62) issue.

Make Fiducials-to-models registration logic available to other python modules

---

BreachWarning/Logic/vtkSlicerBreachWarningLogic.h
BreachWarning/MRML/vtkMRMLBreachWarningNode.h
BreachWarning/qSlicerBreachWarningModule.h
CollectPoints/Logic/vtkSlicerCollectPointsLogic.h
CollectPoints/MRML/vtkMRMLCollectPointsNode.h
CollectPoints/qSlicerCollectPointsModule.h
CreateModels/Logic/vtkSlicerCreateModelsLogic.h
CreateModels/qSlicerCreateModelsModule.h
FiducialRegistrationWizard/Logic/vtkSlicerFiducialRegistrationWizardLogic.h
FiducialRegistrationWizard/MRML/vtkMRMLFiducialRegistrationWizardNode.h
FiducialRegistrationWizard/qSlicerFiducialRegistrationWizardModule.h
PathExplorer/Logic/vtkSlicerPathExplorerLogic.h
PathExplorer/MRML/vtkMRMLPathPlannerTrajectoryNode.h
PathExplorer/qSlicerPathExplorerModule.h
PivotCalibration/Logic/vtkSlicerPivotCalibrationLogic.h
PivotCalibration/qSlicerPivotCalibrationModule.h
TransformProcessor/Logic/vtkSlicerTransformProcessorLogic.h
TransformProcessor/MRML/vtkMRMLTransformProcessorNode.h
TransformProcessor/qSlicerTransformProcessorModule.h
UltrasoundSnapshots/Logic/vtkSlicerUltrasoundSnapshotsLogic.h
UltrasoundSnapshots/qSlicerUltrasoundSnapshotsModule.h
VolumeResliceDriver/Logic/vtkSlicerVolumeResliceDriverLogic.h
VolumeResliceDriver/qSlicerVolumeResliceDriverModule.h
Watchdog/Logic/vtkSlicerWatchdogLogic.h
Watchdog/MRML/vtkMRMLWatchdogDisplayNode.h
Watchdog/MRML/vtkMRMLWatchdogNode.h
Watchdog/MRMLDM/vtkMRMLWatchdogDisplayableManager.h
Watchdog/qSlicerWatchdogModule.h

Adding override specifiers, as these are considered good practice for modern C++ code. Without the specifiers SlicerIGT emits >800 unnecessary warnings on macOS.

COMP: Mark overriding functions with override specifier

---

CMakeLists.txt
PivotCalibration/Logic/CMakeLists.txt
PivotCalibration/Logic/vtkSlicerPivotCalibrationLogic.cxx
PivotCalibration/Logic/vtkSlicerPivotCalibrationLogic.h
PivotCalibration/Testing/Cxx/CMakeLists.txt
PivotCalibration/qSlicerPivotCalibrationModuleWidget.cxx

This commit changes the internal logic of vtkSlicerPivotCalibrationLogic to use the pivot and spin calibration algorithms from IGSIO.
This also provides access to the option to enable automatic calibration from Python. During automatic calibration, the buffer will be filled as the tool moves. If invalid tool motion is detected due to high error in recent poses, then the whole input buffer will be discarded. Once the required number of poses and error threshold is reached, vtkSlicerPivotCalibrationLogic will invoke (Pivot/Spin)CalibrationCompleteEvent. These options are currently not accessible through the GUI.

ENH: Update pivot calibration algorithm to use IGSIO

---

PivotCalibration/Logic/vtkSlicerPivotCalibrationLogic.cxx
PivotCalibration/Logic/vtkSlicerPivotCalibrationLogic.h
PivotCalibration/Resources/UI/qSlicerPivotCalibrationModule.ui
PivotCalibration/qSlicerPivotCalibrationModuleWidget.cxx
PivotCalibration/qSlicerPivotCalibrationModuleWidget.h

Adds widgets for changing pivot/spin auto calibration settings.
Also adds vtkSlicerPivotCalibrationLogic::PivotCalibrationEnabled/SpinCalibrationEnabled flags so that pivot/spin can be enabled/disabled separately.
Slight reorganization of the pivot calibration module layout to move the settings collapsible button below results.
Widget show below:

ENH: Add UI for performing stylus auto-calibration

---

PathExplorer/qSlicerPathExplorerModuleWidget.cxx

This change is related to Slicer/Slicer#6909, which fixes the inclusion of generated (and private) Qt `ui_*` files; this indirectly included some Qt headers, which naturally would be missing. This commit includes the `QTableWidget` that would be required upon merging of Slicer/Slicer#6909. This change works also with Slicer/Slicer#6909 not merged.

ENH: Add QTableWidget to qSlicerPathExplorerModuleWidget

---

Guidelet/GuideletLib/UltraSound.py

An exception is raised when using the Guidelet because the new localization feature was missing an import for `_` in the Ultrasound.py. Fix by adding the respective import.

fix: import i18n in Ultrasound class
